import {uniqueId} from "utils";

export default {
  capacity: 28,
  counts: {
    members_count: 8,
    members_count_display: 4,
    pins_count: 3,
    students_count: 4,
  },
  cover_thumb_url: "https://s3.eu-west-3.amazonaws.com/klassroomdev.eu/asset/klassroom/Klasses/K00IV9ZJN65/3d4706c81659977fca47ff3.thumb.jpg",
  cover_url: "https://s3.eu-west-3.amazonaws.com/klassroomdev.eu/asset/klassroom/Klasses/K00IV9ZJN65/3d4706c81659977fca47ff3.jpg",
  created_by: "U00IUEOJABO",
  end_date: 1549126799000,
  id: "K00IV9ZJN65",
  infos: {
    level: "ms",
    topic: "general",
  },
  is_admin: false,
  is_closed: true,
  is_deleted: false,
  is_disabled: false,
  is_ghost: false,
  is_member: false,
  is_moderator: false,
  is_owner: true,
  is_unlocked: true,
  key: "testtest",
  language: "fr",
  last_activity_date: 1549448026000,
  list_students: {
    "KS00JW7ZAD5X": {
      dob: "2018-07-11",
      first_name: "Webbie",
      gender: "m",
      id: uniqueId(),
      klassID: "K00IV9ZJN65",
      last_name: "Testeur",
      main_image_url: "https://d255ekdjj05c2f.cloudfront.net/asset/klassroom/Profile/Students/S00JLAZTJGK/7f6547b716573ecd6e87fb0_a.jpg",
      objectId: "KS00JW7ZAD5X",
      parentID: "S00JLAZTJGK",
      thumb_image_url: "https://d255ekdjj05c2f.cloudfront.net/asset/klassroom/Profile/Students/S00JLAZTJGK/7f6547b716573ecd6e87fb0.thumb_a.jpg",
      _type: "KRStudent",
    },
    "KS00JW7ZAD5X1": {
      dob: "2018-07-11",
      first_name: "Jack",
      gender: "m",
      id: uniqueId(),
      klassID: "K00IV9ZJN65",
      last_name: "Testeur",
      main_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/11.png",
      objectId: "KS00JW7ZAD5X",
      parentID: "S00JLAZTJGK",
      thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/11.png",
      _type: "KRStudent",
    },
    "KS00JW7ZAD5X2": {
      dob: "2018-07-11",
      first_name: "Pettu",
      gender: "m",
      id: uniqueId(),
      klassID: "K00IV9ZJN65",
      last_name: "Testeur",
      main_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/9.png",
      objectId: "KS00JW7ZAD5X",
      parentID: "S00JLAZTJGK",
      thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/9.png",
      _type: "KRStudent",
    },
    "KS00JW7ZAD5X3": {
      dob: "2018-07-11",
      first_name: "John",
      gender: "m",
      id: uniqueId(),
      klassID: "K00IV9ZJN65",
      last_name: "Testeur",
      main_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/5.png",
      objectId: "KS00JW7ZAD5X",
      parentID: "S00JLAZTJGK",
      thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/5.png",
      _type: "KRStudent",
    },
  },
  members: {
    "U00IUEOJABO": {
      created_at: 1478639105000,

      first_name: "User",
      last_name: "1",
      thumb_image_url: "https://d255ekdjj05c2f.cloudfront.net/asset/klassroom/Profile/Students/S00JLAZTJGK/7f6547b716573ecd6e87fb0.thumb_a.jpg",

      id: uniqueId(),
      is_mute: false,
      klassID: "K00IV9ZJN65",
      objectId: "U00IUEOJABO",
      position: "professeur",
      role: "owner",
      students: {},
      type: "teacher",
      username: "U00IUEOJABO",
    },
    "U00IUEOJAB1": {
      created_at: 1478639105000,
      first_name: "User",
      last_name: "2",
      thumb_image_url: "https://d255ekdjj05c2f.cloudfront.net/asset/klassroom/Profile/Students/S00JLAZTJGK/7f6547b716573ecd6e87fb0.thumb_a.jpg",

      id: uniqueId(),
      is_mute: false,
      klassID: "K00IV9ZJN65",
      objectId: "U00IUEOJABO",
      position: "professeur",
      role: "Administrator",
      students: {},
      type: "teacher",
      username: "U00IUEOJABO",
    },
    "U00IUEOJAB2": {
      created_at: 1478639105000,
      first_name: "User",
      last_name: "3",
      thumb_image_url: "https://d255ekdjj05c2f.cloudfront.net/asset/klassroom/Profile/Students/S00JLAZTJGK/7f6547b716573ecd6e87fb0.thumb_a.jpg",

      id: uniqueId(),
      is_mute: false,
      klassID: "K00IV9ZJN65",
      objectId: "U00IUEOJABO",
      position: "professeur",
      role: "teacher",
      students: {},
      type: "teacher",
      username: "U00IUEOJABO",
    },
    "U00IUEOJAB3": {
      created_at: 1478639105000,
      first_name: "User",
      last_name: "4",
      thumb_image_url: "https://d255ekdjj05c2f.cloudfront.net/asset/klassroom/Profile/Students/S00JLAZTJGK/7f6547b716573ecd6e87fb0.thumb_a.jpg",
      
      id: uniqueId(),
      is_mute: false,
      klassID: "K00IV9ZJN65",
      objectId: "U00IUEOJABO",
      position: "professeur",
      role: "Administrator",
      students: {},
      type: "teacher",
      username: "U00IUEOJABO",
    },
  },
  members_count: 8,
  members_count_display: 4,
  natural_name: "PreK4 Room 103",
  objectId: "K00IV9ZJN65",
  organization: "Ecole primaire privée Pascal",
  organization_zip: "75016",
  pins_count: 3,
}