import {uniqueId} from "utils";
import * as moment from 'moment';

export default {
  newComment: {
      attachments: {},
      date: moment().unix(),
      id: uniqueId(),
      is_edited: false,
      is_valid: true,
      klassID: "K00J5U60NQA",
      postID: "P00JVSH7E9R",
      text: "comment test 1",
      user: {
        first_name: "Damien",
        id: uniqueId(),
        is_available: true,
        last_name: "Testeur",
        name: "Damien Testeur",
        objectId: "U00IUEOJABO",
        properties: {},
        thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/princes/12.png",
        username: "U00IUEOJABO",
        _type: "KRUser",
      },
      userID: "U00IUEOJABO",
      _type: "KRComment",
  },
  pages: [
    // page 1
    {
      page: 0,
      comments: [
        {
          attachments: {},
          date: moment().unix(),
          id: uniqueId(),
          is_edited: false,
          is_valid: true,
          klassID: "K00J5U60NQA",
          postID: "P00JVSH7E9R",
          text: "comment test 1",
          user: {
            first_name: "Damien",
            id: uniqueId(),
            is_available: true,
            last_name: "Testeur",
            name: "Damien Testeur",
            objectId: "U00IUEOJABO",
            properties: {},
            thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/princes/12.png",
            username: "U00IUEOJABO",
            _type: "KRUser",
          },
          userID: "U00IUEOJABO",
          _type: "KRComment",
        },
        {
          attachments: {},
          date: moment().unix(),
          id: uniqueId(),
          is_edited: false,
          is_valid: true,
          klassID: "K00J5U60NQA",
          postID: "P00JVSH7E9R",
          text: "comment test 2",
          user: {
            first_name: "Test",
            id: uniqueId(),
            is_available: true,
            last_name: "User",
            name: "Test User",
            objectId: "U00IUEOJABO",
            properties: {},
            thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/princes/12.png",
            username: "U00IUEOJABO",
            _type: "KRUser",
          },
          userID: "U00IUEOJABO",
          _type: "KRComment",
        },
        {
          attachments: {},
          date: moment().unix(),
          id: uniqueId(),
          is_edited: false,
          is_valid: true,
          klassID: "K00J5U60NQA",
          postID: "P00JVSH7E9R",
          text: "comment test 3",
          user: {
            first_name: "Test",
            id: uniqueId(),
            is_available: true,
            last_name: "User 2",
            name: "Test User 2",
            objectId: "U00IUEOJABO",
            properties: {},
            thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/princes/12.png",
            username: "U00IUEOJABO",
            _type: "KRUser",
          },
          userID: "U00IUEOJABO",
          _type: "KRComment",
        },

      ]
    },
    {
      page: 1,
      comments: [
        {
          attachments: {},
          date: moment().unix(),
          id: uniqueId(),
          is_edited: false,
          is_valid: true,
          klassID: "K00J5U60NQA",
          postID: "P00JVSH7E9R",
          text: "comment test 1",
          user: {
            first_name: "Damien",
            id: uniqueId(),
            is_available: true,
            last_name: "Testeur",
            name: "Damien Testeur",
            objectId: "U00IUEOJABO",
            properties: {},
            thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/princes/12.png",
            username: "U00IUEOJABO",
            _type: "KRUser",
          },
          userID: "U00IUEOJABO",
          _type: "KRComment",
        },
        {
          attachments: {},
          date: moment().unix(),
          id: uniqueId(),
          is_edited: false,
          is_valid: true,
          klassID: "K00J5U60NQA",
          postID: "P00JVSH7E9R",
          text: "comment test 2",
          user: {
            first_name: "Test",
            id: uniqueId(),
            is_available: true,
            last_name: "User",
            name: "Test User",
            objectId: "U00IUEOJABO",
            properties: {},
            thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/princes/12.png",
            username: "U00IUEOJABO",
            _type: "KRUser",
          },
          userID: "U00IUEOJABO",
          _type: "KRComment",
        },
        {
          attachments: {},
          date: moment().unix(),
          id: uniqueId(),
          is_edited: false,
          is_valid: true,
          klassID: "K00J5U60NQA",
          postID: "P00JVSH7E9R",
          text: "comment test 3",
          user: {
            first_name: "Test",
            id: uniqueId(),
            is_available: true,
            last_name: "User 2",
            name: "Test User 2",
            objectId: "U00IUEOJABO",
            properties: {},
            thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/princes/12.png",
            username: "U00IUEOJABO",
            _type: "KRUser",
          },
          userID: "U00IUEOJABO",
          _type: "KRComment",
        },

      ]
    },
    {
      page: 3,
      comments: [
        {
          attachments: {},
          date: moment().unix(),
          id: uniqueId(),
          is_edited: false,
          is_valid: true,
          klassID: "K00J5U60NQA",
          postID: "P00JVSH7E9R",
          text: "comment test 1",
          user: {
            first_name: "Damien",
            id: uniqueId(),
            is_available: true,
            last_name: "Testeur",
            name: "Damien Testeur",
            objectId: "U00IUEOJABO",
            properties: {},
            thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/princes/12.png",
            username: "U00IUEOJABO",
            _type: "KRUser",
          },
          userID: "U00IUEOJABO",
          _type: "KRComment",
        },
        {
          attachments: {},
          date: moment().unix(),
          id: uniqueId(),
          is_edited: false,
          is_valid: true,
          klassID: "K00J5U60NQA",
          postID: "P00JVSH7E9R",
          text: "comment test 2",
          user: {
            first_name: "Test",
            id: uniqueId(),
            is_available: true,
            last_name: "User",
            name: "Test User",
            objectId: "U00IUEOJABO",
            properties: {},
            thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/princes/12.png",
            username: "U00IUEOJABO",
            _type: "KRUser",
          },
          userID: "U00IUEOJABO",
          _type: "KRComment",
        },
        {
          attachments: {},
          date: moment().unix(),
          id: uniqueId(),
          is_edited: false,
          is_valid: true,
          klassID: "K00J5U60NQA",
          postID: "P00JVSH7E9R",
          text: "comment test 3",
          user: {
            first_name: "Test",
            id: uniqueId(),
            is_available: true,
            last_name: "User 2",
            name: "Test User 2",
            objectId: "U00IUEOJABO",
            properties: {},
            thumb_image_url: "https://d357z0wweac9e6.cloudfront.net/avatars/princes/12.png",
            username: "U00IUEOJABO",
            _type: "KRUser",
          },
          userID: "U00IUEOJABO",
          _type: "KRComment",
        },

      ]
    }

  ]
  
}